name = "shumilog-backend"
main = "src/index.ts"
compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
APP_BASE_URL = "http://localhost:5173"
APP_LOGIN_URL = "http://localhost:5173/login"
TWITTER_REDIRECT_URI = "http://localhost:8787/api/auth/callback"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[[d1_databases]]
binding = "DB"
database_name = "shumilog-db-dev"
database_id = "local-shumilog-db-dev"
preview_database_id = "local-shumilog-db-dev"
migrations_dir = "migrations"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "shumilog-images-dev"

[env.development]
name = "shumilog-backend-dev"

[[env.development.d1_databases]]
binding = "DB"
database_name = "shumilog-db-devel"
database_id = "617b5001-c479-48d0-b9a6-202e2b3d51f2"
migrations_dir = "migrations"

[env.development.ai]
binding = "AI"

[[env.development.r2_buckets]]
binding = "IMAGES"
bucket_name = "shumilog-images-devel"

[env.development.vars]
ENVIRONMENT = "development"
APP_BASE_URL = "https://shumilog.dev"
APP_LOGIN_URL = "https://shumilog.dev/login"
TWITTER_REDIRECT_URI = "https://api.shumilog.dev/api/auth/callback"

[env.production]
name = "shumilog-backend"

[[env.production.d1_databases]]
binding = "DB"
database_name = "shumilog-db"
database_id = "c97e1c8a-45cd-4748-8792-3faa6ceb5a41"
migrations_dir = "migrations"

[env.production.ai]
binding = "AI"

[[env.production.r2_buckets]]
binding = "IMAGES"
bucket_name = "shumilog-images"

[env.production.vars]
ENVIRONMENT = "production"
APP_BASE_URL = "https://shumilog.dev"
APP_LOGIN_URL = "https://shumilog.dev/login"
TWITTER_REDIRECT_URI = "https://api.shumilog.dev/api/auth/callback"

# Secrets (configured via wrangler secret put)
# TWITTER_CLIENT_ID
# TWITTER_CLIENT_SECRET
# SESSION_SECRET

[observability.logs]
enabled = true
