openapi: 3.0.3
info:
  title: Hobby Content Review Logging API
  description: API for logging and sharing content reviews with Twitter integration
  version: 1.0.0
servers:
  - url: https://shumilog.example.com/api
    description: Production server
  - url: http://localhost:8787/api
    description: Development server

paths:
  /auth/twitter:
    get:
      summary: Initiate Twitter OAuth flow
      description: Redirects user to Twitter for authentication
      responses:
        '302':
          description: Redirect to Twitter OAuth
          headers:
            Location:
              schema:
                type: string
                example: https://twitter.com/i/oauth2/authorize?...
        '400':
          description: Invalid request parameters

  /auth/callback:
    get:
      summary: Handle Twitter OAuth callback
      description: Process OAuth callback and create user session
      parameters:
        - name: code
          in: query
          required: true
          schema:
            type: string
        - name: state
          in: query
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirect to application with session
          headers:
            Set-Cookie:
              schema:
                type: string
                example: session=token; HttpOnly; Secure
        '401':
          description: Authentication failed

  /auth/logout:
    post:
      summary: Logout user
      description: Invalidate user session
      security:
        - sessionAuth: []
      responses:
        '200':
          description: Successfully logged out
        '401':
          description: Not authenticated

  /users/me:
    get:
      summary: Get current user profile
      security:
        - sessionAuth: []
      responses:
        '200':
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Not authenticated

  /tags:
    get:
      summary: Search and list tags
      parameters:
        - name: parent_id
          in: query
          schema:
            type: string
            description: Filter by parent tag ID
        - name: search
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of tags
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Tag'
                  total:
                    type: integer
                  limit:
                    type: integer
                  offset:
                    type: integer

    post:
      summary: Create new tag
      security:
        - sessionAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagCreate'
      responses:
        '201':
          description: Tag created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '400':
          description: Invalid tag data
        '401':
          description: Not authenticated

  /tags/{tagId}:
    get:
      summary: Get tag details
      parameters:
        - name: tagId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tag details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TagDetail'
        '404':
          description: Tag not found

    put:
      summary: Update tag
      security:
        - sessionAuth: []
      parameters:
        - name: tagId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TagUpdate'
      responses:
        '200':
          description: Tag updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '401':
          description: Not authenticated
        '403':
          description: Not tag owner
        '404':
          description: Tag not found

    delete:
      summary: Delete tag
      security:
        - sessionAuth: []
      parameters:
        - name: tagId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Tag deleted
        '401':
          description: Not authenticated
        '403':
          description: Not tag owner
        '404':
          description: Tag not found


  /reviews:
    get:
      summary: List public reviews
      parameters:
        - name: tag_ids
          in: query
          schema:
            type: array
            items:
              type: string
            description: Filter by associated tag IDs
        - name: user_id
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of public reviews
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Review'
                  total:
                    type: integer

    post:
      summary: Create new review
      security:
        - sessionAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewCreate'
      responses:
        '201':
          description: Review created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '400':
          description: Invalid review data
        '401':
          description: Not authenticated

  /reviews/{reviewId}:
    get:
      summary: Get review details
      parameters:
        - name: reviewId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Review details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewDetail'
        '404':
          description: Review not found

    put:
      summary: Update review
      security:
        - sessionAuth: []
      parameters:
        - name: reviewId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewUpdate'
      responses:
        '200':
          description: Review updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        '401':
          description: Not authenticated
        '403':
          description: Not review owner
        '404':
          description: Review not found

    delete:
      summary: Delete review
      security:
        - sessionAuth: []
      parameters:
        - name: reviewId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Review deleted
        '401':
          description: Not authenticated
        '403':
          description: Not review owner
        '404':
          description: Review not found

  /reviews/{reviewId}/share:
    post:
      summary: Share review to Twitter
      security:
        - sessionAuth: []
      parameters:
        - name: reviewId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully shared to Twitter
          content:
            application/json:
              schema:
                type: object
                properties:
                  twitter_post_id:
                    type: string
        '401':
          description: Not authenticated
        '403':
          description: Not review owner
        '404':
          description: Review not found

components:
  securitySchemes:
    sessionAuth:
      type: apiKey
      in: cookie
      name: session

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        twitter_username:
          type: string
        display_name:
          type: string
        avatar_url:
          type: string
        created_at:
          type: string
          format: date-time

    Tag:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        parent_id:
          type: string
          description: Parent tag ID for hierarchical relationships
        metadata:
          type: object
          description: Flexible metadata storage
        created_by:
          type: string
          description: User ID who created this tag
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    TagCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 200
        description:
          type: string
        parent_id:
          type: string
        metadata:
          type: object

    TagUpdate:
      type: object
      properties:
        title:
          type: string
          maxLength: 200
        description:
          type: string
        metadata:
          type: object

    TagDetail:
      allOf:
        - $ref: '#/components/schemas/Tag'
        - type: object
          properties:
            review_count:
              type: integer
            average_rating:
              type: number
            recent_reviews:
              type: array
              items:
                $ref: '#/components/schemas/Review'
            children:
              type: array
              items:
                $ref: '#/components/schemas/Tag'

    Review:
      type: object
      properties:
        id:
          type: string
        user:
          $ref: '#/components/schemas/User'
        associated_tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          description: Tags associated with this review
        title:
          type: string
        content_html:
          type: string
        rating:
          type: integer
          minimum: 1
          maximum: 5
        user_tags:
          type: array
          items:
            type: string
          description: User-defined tags for categorization
        posted_to_twitter:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ReviewCreate:
      type: object
      required:
        - tag_ids
        - content_md
      properties:
        tag_ids:
          type: array
          items:
            type: string
          description: IDs of tags to associate with this review
          minItems: 1
        title:
          type: string
          maxLength: 200
        content_md:
          type: string
          maxLength: 10000
        is_public:
          type: boolean
          default: false
        rating:
          type: integer
          minimum: 1
          maximum: 5
        user_tags:
          type: array
          items:
            type: string
          description: User-defined tags for categorization

    ReviewUpdate:
      type: object
      properties:
        tag_ids:
          type: array
          items:
            type: string
          description: Update the tags associated with this review
        title:
          type: string
          maxLength: 200
        content_md:
          type: string
          maxLength: 10000
        is_public:
          type: boolean
        rating:
          type: integer
          minimum: 1
          maximum: 5
        user_tags:
          type: array
          items:
            type: string
          description: User-defined tags for categorization

    ReviewDetail:
      allOf:
        - $ref: '#/components/schemas/Review'
        - type: object
          properties:
            content_md:
              type: string